### ISSUE TITLE
Can't handle submodules

### ISSUE THREAD

**Issue by onnimonni** [ExpandedFronts/revisr#22]
Revisr doesn't handle another repositorys inside main repository. Preferred actions would be to:

* notice different git repo and give a notice message in wp-admin that revisr is not compatible.
* Ask to merge it into the same repository (git subtree)
* Add it as submodule

**Comment by mgshaw** [comment]
Hi,

Thanks for reporting this. Looking into this further and will keep you posted.

**Comment by ramielbarsoum** [comment]
I wonder if this applies to the following condition:

Version 1.9.3 
On Multisite Install

Wordpress Core is in custom directory.
define( 'REVISR_GIT_DIR', dirname( __FILE__ ) ); in wp-config

It seems revisor is still getting the .git config from the submoduled custom core wp directory.

Example:
/
/.git
/wp/.git (called in as a submodule)
/content
/wp-config.php

In the dashboard, even with the define, it seems revisr is tracking the submodule commits.

is there a way to ignore the wp .git and only use the one at root dir defined in wp-config?

**Comment by mgshaw** [comment]
Hi,

That's strange - the expected behavior here is that it will treat whatever directory is defined as the 'REVISR_GIT_DIR' as the repo - so if you have it set to the main directory, it should pick that up, and should only pick up the submodule if you set it to that submodule. It sounds like that's not how it's working for you though, so I'll look into this further.

I'm thinking the appropriate solution for this is to use the git work tree and git dir parameters that can be passed directly to git, instead of using chdir to select the correct repo. That paves the way for a possible submodule management page and should resolve any issues with picking up the wrong repo.
