### ISSUE TITLE
Changes made outside of Revisr are not seen by Revisr

### ISSUE THREAD

**Issue by vincentml** [ExpandedFronts/Revisr#52]
I updated .gitignore on disk and committed the changes myself. In Revisr's settings page the .gitignore shown doesn't contain my changes. It seems that Revisr has a separate copy of .gitignore. This could lead to unexpected problems. For example, Revisr could overwrite my edited .gitignore with it's copy which is an older version. 

Could Revisr always read .gitignore from disk instead of holding a copy?

I noticed other similar problems. Changes I make directly to git remote configuration are not reflected in Revisr's settings. Commits that I make outside of Revisr are not displayed in Revisr.

**Comment by mgshaw** [comment]
Yep, this is due to a transition from using WordPress settings to using Git due to the benefits of being able to have environment-specific config no matter what a user's DB tracking settings are. 

Some of the old logic remains (without going through commit logs, I think the reasoning was for maintaining backwards-compatibility). This obviously needs to be refactored and I'll aim to have that done for the next release.

**Comment by mgshaw** [comment]
Hi,

This now should be partially fixed (updating gitignore or remote manually will now update in Revisr).

Leaving this open while the remaining issues are addressed.

**Comment by mgshaw** [comment]
This has been completely addressed with 2.0. Now nothing is pulled from the database and all is pulled directly from Git (commits, config, gitignore, etc.).
