### ISSUE TITLE
GitLab.com Private Token for Security

### ISSUE THREAD

**Issue by JosefJezek** [ExpandedFronts/revisr#62]
Could you add support for GitLab.com Private Token? This token save as option in DB.

Check out this nice plugin https://github.com/afragen/github-updater

- http://doc.gitlab.com/ce/api/

**Comment by mgshaw** [comment]
Thanks for the suggestion. Will look into this further.

**Comment by roggershaw** [comment]
I am also looking into it. Thanks

**Comment by mgshaw** [comment]
@JosefJezek So it looks like the private token is just for Gitlab API, correct?

This plugin doesn't yet use any APIs from Bitbucket/GitHub/Gitlab, and instead uses standard Git protocol/SSH to push changes to those remote repos, since that is much more consistent across Git hosts.

I did test Revisr with the Gitlab hosted version and everything was working well via SSH.

Did you have a specific use-case for using the API?
