### ISSUE TITLE
Debugging 'Error backing up the database.'

### ISSUE THREAD

**Issue by jonlambert** [ExpandedFronts/revisr#75]
Hi,

How could I debug the error I'm receiving? 'Error backing up the database.'
Is the error logged with more verbosity anywhere?

Thanks!

**Comment by mgshaw** [comment]
Hi Jon,

You should be able to see what's going on by checking the value for the "MySQL Path" in the settings.

You likely just need to add the path to mysql as shown in the documentation here:
http://docs.revisr.io/article/14-database-settings

Alternatively you could set it to use WordPress as the database driver if you're not working with a very large database.

Hope that helps!

**Comment by jonlambert** [comment]
Hi, thanks for your reply. I'm not sure how this will help me get the actual error, though?

**Comment by jonlambert** [comment]
Or does that error just point to one thing, no MySQL path?

**Comment by mgshaw** [comment]
The vast majority of the time it would be the lack of the MySQL path, although it can also be triggered when the verify_backup function fails (if the file doesn't exist or is under 100 bytes).

If using MySQL depending on your debug settings the errors may appear in the otherwise empty SQL files- this would still be under 100 bytes in the majority of the time and would trigger the 'Error backing up the database' message.

Other than that, there's no real verbosity to the error - this is obviously something that could be improved so I'll leave this open as a reminder for that to get addressed.

**Comment by phidodido** [comment]
The documentation doesn't exist anymore http://docs.revisr.io/article/14-database-settings
I have tried this path C:\xampplite\mysql\bin but it still gives the database backup error. Backing up with the WordPress database driver does work though.

**Comment by WeeSee** [comment]
Don't know if this issue is still seeking solutions. I had the same problem and this was the problem:

The linux file permissions in ```/wp-content/uploads/revisr-backups``` of two files from 21 files were wrong. I made a ```chown``` and modified them by hand. 

Everything works now like charme again.
