### ISSUE TITLE
how hide Remote URL credentials?

### ISSUE THREAD

**Issue by dennisfranck** [ExpandedFronts/revisr#90]
By using the Revisr for backups on a website, it was interesting that the Remote URL credentials fields stay hidden or masked.

**Comment by ghost** [comment]
Having the same issue. Any updates on this?

**Comment by jhoughtelin** [comment]
If you don't authenticate over HTTPS you don't need to store your and password in the Remote URL field.  You only need to use the username and password in the URL if you use the HTTPS://user:pass@bitbucket-github.com method.  For all the WordPress sites I use revisr with I setup ssh key pairs for access.  

It's pretty easy, just SSH in to the server hosting the WordPress site and then switch to whatever the web server uses as a user, in some cases it's `www-data`.  Generate an ssh key pair for that user `ssh-keygen` and copy the public key in to your team or your personal authorized key pairs so then whatever user the web server is running as can use git over ssh rather than http. You'll know it's setup properly when you are actively logged in as the user that the web server operates as and you can execute git commands with being prompted for a password.
